In [1]:
import pandas as pd
import numpy as np

%matplotlib inline

In [2]:
df = pd.read_csv("wafflehouses/wafflehouses.csv")

In [3]:
df.shape

(1803, 4)

In [4]:
df.dtypes

location     object
lat         float64
long        float64
score         int64
dtype: object

In [5]:
df.head()

                    location        lat       long  score
0     Waffle House-Duluth,GA  33.991269 -84.153232      8
1     Waffle House-Biloxi,MS  30.393627 -88.942691      3
2      Waffle House-Pearl,MS  32.269078 -90.135180      3
3    Waffle House-Memphis,TN  35.155903 -89.885466      2
4  Waffle House-Lumberton,TX  30.242025 -94.195967      2

In [6]:
df[df.location.str.contains(",GA")].shape

(416, 4)

In [7]:
# List Slicing
numbers = [1, 2, 3, 4, 5, 6, 7, 8, 9]
# numbers[0:5]  Starting at the first number ('0') get the next five things
# numbers[3:6]  Gets 4, 5, 6
# numbers[-3:]  Third last through whatever
sentence = "hello soma"
# sentence[0:5]

In [8]:
# df.location.str.contains("WV")
# df.location.str.replace("WV", "West Virginia")
# df.location.str.contains("WV")
# df.location.str.contains("WV")

In [9]:
# this will find stuff but doesn't work, python needs to know what to do, what we wany to keep
# df.location.str.extract(,.*)

In [10]:
# needs quotes brackets, quotes
df.location.str.extract(",(.*)")

       0
0     GA
1     MS
2     MS
3     TN
4     TX
5     AL
6     DE
7     GA
8     TN
9     AL
10    AL
11    AL
12    AL
13    AL
14    AL
15    AL
16    AL
17    AL
18    AL
19    AL
20    AL
21    AL
22    AL
23    AL
24    AL
25    AL
26    AL
27    AL
28    AL
29    AL
...   ..
1773  VA
1774  VA
1775  VA
1776  VA
1777  VA
1778  VA
1779  VA
1780  VA
1781  VA
1782  VA
1783  VA
1784  VA
1785  VA
1786  VA
1787  VA
1788  VA
1789  VA
1790  VA
1791  VA
1792  VA
1793  VA
1794  VA
1795  VA
1796  VA
1797  VA
1798  VA
1799  WV
1800  WV
1801  WV
1802  WV

[1803 rows x 1 columns]

In [11]:
# needs quotes brackets, quotes
df['state_abbr'] = df.location.str.extract(",(.*)")

In [12]:
df.head()

                    location        lat       long  score state_abbr
0     Waffle House-Duluth,GA  33.991269 -84.153232      8         GA
1     Waffle House-Biloxi,MS  30.393627 -88.942691      3         MS
2      Waffle House-Pearl,MS  32.269078 -90.135180      3         MS
3    Waffle House-Memphis,TN  35.155903 -89.885466      2         TN
4  Waffle House-Lumberton,TX  30.242025 -94.195967      2         TX

In [13]:
df.location.str.split(",")[0]

['Waffle House-Duluth', 'GA']

In [14]:
df.location.str.split(",").str.get(-1)

0       GA
1       MS
2       MS
3       TN
4       TX
5       AL
6       DE
7       GA
8       TN
9       AL
10      AL
11      AL
12      AL
13      AL
14      AL
15      AL
16      AL
17      AL
18      AL
19      AL
20      AL
21      AL
22      AL
23      AL
24      AL
25      AL
26      AL
27      AL
28      AL
29      AL
        ..
1773    VA
1774    VA
1775    VA
1776    VA
1777    VA
1778    VA
1779    VA
1780    VA
1781    VA
1782    VA
1783    VA
1784    VA
1785    VA
1786    VA
1787    VA
1788    VA
1789    VA
1790    VA
1791    VA
1792    VA
1793    VA
1794    VA
1795    VA
1796    VA
1797    VA
1798    VA
1799    WV
1800    WV
1801    WV
1802    WV
Name: location, Length: 1803, dtype: object

In [15]:
df.state_abbr.value_counts()

GA    416
NC    166
SC    163
FL    152
AL    147
TN    113
TX    105
MS     87
LA     79
OH     72
KY     63
VA     50
AR     44
MO     40
IN     24
AZ     17
OK     16
PA     11
MD     11
CO     10
KS      5
WV      4
DE      3
NM      2
IL      2
Name: state_abbr, dtype: int64

In [16]:
populations = pd.read_excel("wafflehouses/nst-est2016-01.xlsx")

In [17]:
populations.head()

,table with row headers in column A and column headers in rows 3 through 4. (leading dots indicate sub-parts),Unnamed: 1,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,Unnamed: 9
0,Table 1. Annual Estimates of the Resident Popu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,Geographic Area,2010-04-01 00:00:00,NaN,Population Estimate (as of July 1),NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,Census,Estimates Base,2010,2011.0,2012.0,2013.0,2014.0,2015.0,2016.0
3,United States,308745538,308758105,309348193,311663358.0,313998379.0,316204908.0,318563456.0,320896618.0,323127513.0
4,Northeast,55317240,55318353,55388056,55632766.0,55829059.0,55988771.0,56116791.0,56184737.0,56209510.0

In [18]:
pop_df = pd.read_excel("wafflehouses/nst-est2016-01.xlsx", skiprows=3, skipfooter=7)

In [19]:
pop_df.head()

,Unnamed: 0,Census,Estimates Base,2010,2011,2012,2013,2014,2015,2016
0,United States,308745538,308758105,309348193,311663358,313998379,316204908,318563456,320896618,323127513
1,Northeast,55317240,55318353,55388056,55632766,55829059,55988771,56116791,56184737,56209510
2,Midwest,66927001,66929825,66978602,67153331,67332320,67543948,67726368,67838387,67941429
3,South,114555744,114563005,114863114,116061801,117299171,118424320,119696311,121039206,122319574
4,West,71945553,71946922,72118421,72815460,73537829,74247869,75023986,75834288,76657000

In [20]:
pop_df = pop_df.rename(columns={
    "Unnamed: 0": "State"
})
pop_df.head(10)

,State,Census,Estimates Base,2010,2011,2012,2013,2014,2015,2016
0,United States,308745538,308758105,309348193,311663358,313998379,316204908,318563456,320896618,323127513
1,Northeast,55317240,55318353,55388056,55632766,55829059,55988771,56116791,56184737,56209510
2,Midwest,66927001,66929825,66978602,67153331,67332320,67543948,67726368,67838387,67941429
3,South,114555744,114563005,114863114,116061801,117299171,118424320,119696311,121039206,122319574
4,West,71945553,71946922,72118421,72815460,73537829,74247869,75023986,75834288,76657000
5,.Alabama,4779736,4780131,4785492,4799918,4815960,4829479,4843214,4853875,4863300
6,.Alaska,710231,710249,714031,722713,731089,736879,736705,737709,741894
7,.Arizona,6392017,6392301,6408312,6467163,6549634,6624617,6719993,6817565,6931071
8,.Arkansas,2915918,2916025,2921995,2939493,2950685,2958663,2966912,2977853,2988248
9,.California,37253956,37254522,37332685,37676861,38011074,38335203,38680810,38993940,39250017

In [21]:
pop_df['State'] = pop_df.State.str.replace(".","")
pop_df.head(10)

,State,Census,Estimates Base,2010,2011,2012,2013,2014,2015,2016
0,United States,308745538,308758105,309348193,311663358,313998379,316204908,318563456,320896618,323127513
1,Northeast,55317240,55318353,55388056,55632766,55829059,55988771,56116791,56184737,56209510
2,Midwest,66927001,66929825,66978602,67153331,67332320,67543948,67726368,67838387,67941429
3,South,114555744,114563005,114863114,116061801,117299171,118424320,119696311,121039206,122319574
4,West,71945553,71946922,72118421,72815460,73537829,74247869,75023986,75834288,76657000
5,Alabama,4779736,4780131,4785492,4799918,4815960,4829479,4843214,4853875,4863300
6,Alaska,710231,710249,714031,722713,731089,736879,736705,737709,741894
7,Arizona,6392017,6392301,6408312,6467163,6549634,6624617,6719993,6817565,6931071
8,Arkansas,2915918,2916025,2921995,2939493,2950685,2958663,2966912,2977853,2988248
9,California,37253956,37254522,37332685,37676861,38011074,38335203,38680810,38993940,39250017

In [22]:
abbr_df = pd.read_excel("wafflehouses/abbreviations.xlsx")

In [23]:
abbr_df.head(10)

          name abbreviation
0      Alabama           AL
1       Alaska           AK
2      Arizona           AZ
3     Arkansas           AR
4   California           CA
5     Colorado           CO
6  Connecticut           CT
7     Delaware           DE
8      Florida           FL
9      Georgia           GA

In [30]:
df.merge(abbr_df, left_on='state_abbr', right_on='abbreviation')

,location,lat,long,score,state_abbr,name,abbreviation
0,"Waffle House-Duluth,GA",33.991269,-84.153232,8,GA,Georgia,GA
1,"Waffle House-Darien,GA",31.386768,-81.427065,8,GA,Georgia,GA
2,"Waffle House-Acworth,GA",34.081955,-84.654650,7,GA,Georgia,GA
3,"Waffle House-Acworth,GA",34.000414,-84.704073,8,GA,Georgia,GA
4,"Waffle House-Acworth,GA",34.034899,-84.679145,10,GA,Georgia,GA
5,"Waffle House-Acworth,GA",34.076174,-84.652734,9,GA,Georgia,GA
6,"Waffle House-Acworth,GA",34.078471,-84.676401,6,GA,Georgia,GA
7,"Waffle House-Acworth,GA",34.087328,-84.576863,10,GA,Georgia,GA
8,"Waffle House-Adairsville,GA",34.376978,-84.916670,5,GA,Georgia,GA
9,"Waffle House-Adel,GA",31.134507,-83.435808,9,GA,Georgia,GA
10,"Waffle House-Albany,GA",31.592573,-84.202957,9,GA,Georgia,GA
11,"Waffle House-Albany,GA",31.570771,-84.107076,7,GA,Georgia,GA
12,"Waffle House-Albany,GA",31.616962,-84.222709,8,GA,Georgia,GA
13,"Waffle House-Alpharetta,GA",34.085350,-84.359189,7,GA,Georgia,GA
14,"Waffle House-Alpharetta,GA",34.110778,-84.220001,9,GA,Georgia,GA
15,"Waffle House-Alpharetta,GA",33.991620,-84.278344,6,GA,Georgia,GA
16,"Waffle House-Alpharetta,GA",34.037521,-84.296644,6,GA,Georgia,GA
17,"Waffle House-Alpharetta,GA",34.068702,-84.267842,9,GA,Georgia,GA
18,"Waffle House-Alpharetta,GA",34.066220,-84.310374,7,GA,Georgia,GA
19,"Waffle House-Americus,GA",32.060998,-84.204571,8,GA,Georgia,GA
20,"Waffle House-Ashburn,GA",31.710728,-83.640108,9,GA,Georgia,GA
21,"Waffle House-Athens,GA",33.938868,-83.386409,6,GA,Georgia,GA
22,"Waffle House-Athens,GA",33.947986,-83.358392,5,GA,Georgia,GA
23,"Waffle House-Athens,GA",33.957967,-83.377706,5,GA,Georgia,GA
24,"Waffle House-Athens,GA",33.951736,-83.408995,6,GA,Georgia,GA
25,"Waffle House-Athens,GA",33.926353,-83.339821,6,GA,Georgia,GA
26,"Waffle House-Athens,GA",33.924341,-83.378542,6,GA,Georgia,GA
27,"Waffle House-Athens,GA",33.986437,-83.345708,5,GA,Georgia,GA
28,"Waffle House-Athens,GA",33.889109,-83.413506,5,GA,Georgia,GA
29,"Waffle House-Atlanta,GA",33.751405,-84.385420,10,GA,Georgia,GA
...,...,...,...,...,...,...,...
1772,"Waffle House-Newport News,VA",37.113545,-76.500962,8,VA,Virginia,VA
1773,"Waffle House-Newport News,VA",37.044735,-76.459175,6,VA,Virginia,VA
1774,"Waffle House-Newport News,VA",37.140556,-76.518775,6,VA,Virginia,VA
1775,"Waffle House-Newport News,VA",37.096626,-76.458935,8,VA,Virginia,VA
1776,"Waffle House-Norfolk,VA",36.855685,-76.207546,7,VA,Virginia,VA
1777,"Waffle House-North Chesterfield,VA",37.471721,-77.526466,3,VA,Virginia,VA
1778,"Waffle House-North Chesterfield,VA",37.499386,-77.534395,8,VA,Virginia,VA
1779,"Waffle House-Petersburg,VA",37.195245,-77.468591,2,VA,Virginia,VA
1780,"Waffle House-Richmond,VA",37.553006,-77.454299,6,VA,Virginia,VA
1781,"Waffle House-Richmond,VA",37.401733,-77.422706,8,VA,Virginia,VA
1782,"Waffle House-Richmond,VA",37.517619,-77.344316,7,VA,Virginia,VA
1783,"Waffle House-Richmond,VA",37.610945,-77.519675,4,VA,Virginia,VA
1784,"Waffle House-Richmond,VA",37.470908,-77.528366,7,VA,Virginia,VA
1785,"Waffle House-Roanoke,VA",37.235660,-79.969926,6,VA,Virginia,VA
1786,"Waffle House-Roanoke,VA",37.326124,-79.991347,2,VA,Virginia,VA
1787,"Waffle House-Roanoke,VA",37.327174,-79.992217,6,VA,Virginia,VA
1788,"Waffle House-Ruther Glen,VA",37.935184,-77.474388,7,VA,Virginia,VA
1789,"Waffle House-Sandston,VA",37.518066,-77.339776,7,VA,Virginia,VA
1790,"Waffle House-Staunton,VA",38.133901,-79.042422,6,VA,Virginia,VA
1791,"Waffle House-Stephens City,VA",39.080816,-78.213600,4,VA,Virginia,VA
1792,"Waffle House-Virginia Beach,VA",36.804371,-76.189016,4,VA,Virginia,VA
1793,"Waffle House-Virginia Beach,VA",36.881254,-76.186480,4,VA,Virginia,VA
1794,"Waffle House-Waynesboro,VA",38.064635,-78.937771,1,VA,Virginia,VA
1795,"Waffle House-Winchester,VA",39.186852,-78.130910,2,VA,Virginia,VA
1796,"Waffle House-Winchester,VA",39.165409,-78.165002,7,VA,Virginia,VA
1797,"Waffle House-Wytheville,VA",36.947852,-81.057175,6,VA,Virginia,VA
1798,"Waffle House-Huntington,WV",38.412195,-82.364098,2,WV,West Virginia,WV
1799,"Waffle House-Inwood,WV",39.362366,-78.043392,6,WV,West Virginia,WV
1800,"Waffle House-Martinsburg,WV",39.445517,-77.986999,4,WV,West Virginia,WV
1801,"Waffle House-Martinsburg,WV",39.486633,-77.957717,2,WV,West Virginia,WV

In [36]:
merged = df.merge(abbr_df, left_on='state_abbr', right_on='abbreviation')
merged.head()

,location,lat,long,score,state_abbr,name,abbreviation
0,"Waffle House-Duluth,GA",33.991269,-84.153232,8,GA,Georgia,GA
1,"Waffle House-Darien,GA",31.386768,-81.427065,8,GA,Georgia,GA
2,"Waffle House-Acworth,GA",34.081955,-84.654650,7,GA,Georgia,GA
3,"Waffle House-Acworth,GA",34.000414,-84.704073,8,GA,Georgia,GA
4,"Waffle House-Acworth,GA",34.034899,-84.679145,10,GA,Georgia,GA

In [38]:
merged.merge(pop_df, left_on='name', right_on='State')

,location,lat,long,score,state_abbr,name,abbreviation,State,Census,Estimates Base,2010,2011,2012,2013,2014,2015,2016
0,"Waffle House-Duluth,GA",33.991269,-84.153232,8,GA,Georgia,GA,Georgia,9687653,9688680,9713521,9811610,9914668,9984938,10087231,10199398,10310371
1,"Waffle House-Darien,GA",31.386768,-81.427065,8,GA,Georgia,GA,Georgia,9687653,9688680,9713521,9811610,9914668,9984938,10087231,10199398,10310371
2,"Waffle House-Acworth,GA",34.081955,-84.654650,7,GA,Georgia,GA,Georgia,9687653,9688680,9713521,9811610,9914668,9984938,10087231,10199398,10310371
3,"Waffle House-Acworth,GA",34.000414,-84.704073,8,GA,Georgia,GA,Georgia,9687653,9688680,9713521,9811610,9914668,9984938,10087231,10199398,10310371
4,"Waffle House-Acworth,GA",34.034899,-84.679145,10,GA,Georgia,GA,Georgia,9687653,9688680,9713521,9811610,9914668,9984938,10087231,10199398,10310371
5,"Waffle House-Acworth,GA",34.076174,-84.652734,9,GA,Georgia,GA,Georgia,9687653,9688680,9713521,9811610,9914668,9984938,10087231,10199398,10310371
6,"Waffle House-Acworth,GA",34.078471,-84.676401,6,GA,Georgia,GA,Georgia,9687653,9688680,9713521,9811610,9914668,9984938,10087231,10199398,10310371
7,"Waffle House-Acworth,GA",34.087328,-84.576863,10,GA,Georgia,GA,Georgia,9687653,9688680,9713521,9811610,9914668,9984938,10087231,10199398,10310371
8,"Waffle House-Adairsville,GA",34.376978,-84.916670,5,GA,Georgia,GA,Georgia,9687653,9688680,9713521,9811610,9914668,9984938,10087231,10199398,10310371
9,"Waffle House-Adel,GA",31.134507,-83.435808,9,GA,Georgia,GA,Georgia,9687653,9688680,9713521,9811610,9914668,9984938,10087231,10199398,10310371
10,"Waffle House-Albany,GA",31.592573,-84.202957,9,GA,Georgia,GA,Georgia,9687653,9688680,9713521,9811610,9914668,9984938,10087231,10199398,10310371
11,"Waffle House-Albany,GA",31.570771,-84.107076,7,GA,Georgia,GA,Georgia,9687653,9688680,9713521,9811610,9914668,9984938,10087231,10199398,10310371
12,"Waffle House-Albany,GA",31.616962,-84.222709,8,GA,Georgia,GA,Georgia,9687653,9688680,9713521,9811610,9914668,9984938,10087231,10199398,10310371
13,"Waffle House-Alpharetta,GA",34.085350,-84.359189,7,GA,Georgia,GA,Georgia,9687653,9688680,9713521,9811610,9914668,9984938,10087231,10199398,10310371
14,"Waffle House-Alpharetta,GA",34.110778,-84.220001,9,GA,Georgia,GA,Georgia,9687653,9688680,9713521,9811610,9914668,9984938,10087231,10199398,10310371
15,"Waffle House-Alpharetta,GA",33.991620,-84.278344,6,GA,Georgia,GA,Georgia,9687653,9688680,9713521,9811610,9914668,9984938,10087231,10199398,10310371
16,"Waffle House-Alpharetta,GA",34.037521,-84.296644,6,GA,Georgia,GA,Georgia,9687653,9688680,9713521,9811610,9914668,9984938,10087231,10199398,10310371
17,"Waffle House-Alpharetta,GA",34.068702,-84.267842,9,GA,Georgia,GA,Georgia,9687653,9688680,9713521,9811610,9914668,9984938,10087231,10199398,10310371
18,"Waffle House-Alpharetta,GA",34.066220,-84.310374,7,GA,Georgia,GA,Georgia,9687653,9688680,9713521,9811610,9914668,9984938,10087231,10199398,10310371
19,"Waffle House-Americus,GA",32.060998,-84.204571,8,GA,Georgia,GA,Georgia,9687653,9688680,9713521,9811610,9914668,9984938,10087231,10199398,10310371
20,"Waffle House-Ashburn,GA",31.710728,-83.640108,9,GA,Georgia,GA,Georgia,9687653,9688680,9713521,9811610,9914668,9984938,10087231,10199398,10310371
21,"Waffle House-Athens,GA",33.938868,-83.386409,6,GA,Georgia,GA,Georgia,9687653,9688680,9713521,9811610,9914668,9984938,10087231,10199398,10310371
22,"Waffle House-Athens,GA",33.947986,-83.358392,5,GA,Georgia,GA,Georgia,9687653,9688680,9713521,9811610,9914668,9984938,10087231,10199398,10310371
23,"Waffle House-Athens,GA",33.957967,-83.377706,5,GA,Georgia,GA,Georgia,9687653,9688680,9713521,9811610,9914668,9984938,10087231,10199398,10310371
24,"Waffle House-Athens,GA",33.951736,-83.408995,6,GA,Georgia,GA,Georgia,9687653,9688680,9713521,9811610,9914668,9984938,10087231,10199398,10310371
25,"Waffle House-Athens,GA",33.926353,-83.339821,6,GA,Georgia,GA,Georgia,9687653,9688680,9713521,9811610,9914668,9984938,10087231,10199398,10310371
26,"Waffle House-Athens,GA",33.924341,-83.378542,6,GA,Georgia,GA,Georgia,9687653,9688680,9713521,9811610,9914668,9984938,10087231,10199398,10310371
27,"Waffle House-Athens,GA",33.986437,-83.345708,5,GA,Georgia,GA,Georgia,9687653,9688680,9713521,9811610,9914668,9984938,10087231,10199398,10310371
28,"Waffle House-Athens,GA",33.889109,-83.413506,5,GA,Georgia,GA,Georgia,9687653,9688680,9713521,9811610,9914668,9984938,10087231,10199398,10310371
29,"Waffle House-Atlanta,GA",33.751405,-84.385420,10,GA,Georgia,GA,Georgia,9687653,9688680,9713521,9811610,9914668,9984938,10087231,10199398,10310371
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1772,"Waffle House-Newport News,VA",37.113545,-76.500962,8,VA,Virginia,VA,Virginia,8001024,8001041,8025773,8110035,8192048,8262692,8317372,8367587,8411808
1773,"Waffle House-Newport News,VA",37.044735,-76.459175,6,VA,Virginia,VA,Virginia,8001024,8001041,8025773,8110035,8192048,8262692,8317372,8367587,8411808
1774,"Waffle House-Newport News,VA",37.140556,-76.518775,6,VA,Virginia,VA,Virginia,8001024,8001041,8025773,8110035,8192048,8262692,8317372,8367587,8411808
1775,"Waffle House-Newport News,VA",37.096626,-76.458935,8,VA,Virginia,VA,Virginia,8001024,8001041,8025773,8110035,8192048,8262692,8317372,8367587,8411808
1776,"Waffle House-Norfolk,VA",36.855685,-76.207546,7,VA,Virginia,VA,Virginia,8001024,8001041,8025773,8110035,8192048,8262692,8317372,8367587,8411808
1777,"Waffle House-North Chesterfield,VA",37.471721,-77.526466,3,VA,Virginia,VA,Virginia,8001024,8001041,8025773,8110035,8192048,8262692,8317372,8367587,8411808
1778,"Waffle House-North Chesterfield,VA",37.499386,-77.534395,8,VA,Virginia,VA,Virginia,8001024,8001041,8025773,8110035,8192048,8262692,8317372,8367587,8411808
1779,"Waffle House-Petersburg,VA",37.195245,-77.468591,2,VA,Virginia,VA,Virginia,8001024,8001041,8025773,8110035,8192048,8262692,8317372,8367587,8411808
1780,"Waffle House-Richmond,VA",37.553006,-77.454299,6,VA,Virginia,VA,Virginia,8001024,8001041,8025773,8110035,8192048,8262692,8317372,8367587,8411808
1781,"Waffle House-Richmond,VA",37.401733,-77.422706,8,VA,Virginia,VA,Virginia,8001024,8001041,8025773,8110035,8192048,8262692,8317372,8367587,8411808
1782,"Waffle House-Richmond,VA",37.517619,-77.344316,7,VA,Virginia,VA,Virginia,8001024,8001041,8025773,8110035,8192048,8262692,8317372,8367587,8411808
1783,"Waffle House-Richmond,VA",37.610945,-77.519675,4,VA,Virginia,VA,Virginia,8001024,8001041,8025773,8110035,8192048,8262692,8317372,8367587,8411808
1784,"Waffle House-Richmond,VA",37.470908,-77.528366,7,VA,Virginia,VA,Virginia,8001024,8001041,8025773,8110035,8192048,8262692,8317372,8367587,8411808
1785,"Waffle House-Roanoke,VA",37.235660,-79.969926,6,VA,Virginia,VA,Virginia,8001024,8001041,8025773,8110035,8192048,8262692,8317372,8367587,8411808
1786,"Waffle House-Roanoke,VA",37.326124,-79.991347,2,VA,Virginia,VA,Virginia,8001024,8001041,8025773,8110035,8192048,8262692,8317372,8367587,8411808
1787,"Waffle House-Roanoke,VA",37.327174,-79.992217,6,VA,Virginia,VA,Virginia,8001024,8001041,8025773,8110035,8192048,8262692,8317372,8367587,8411808
1788,"Waffle House-Ruther Glen,VA",37.935184,-77.474388,7,VA,Virginia,VA,Virginia,8001024,8001041,8025773,8110035,8192048,8262692,8317372,8367587,8411808
1789,"Waffle House-Sandston,VA",37.518066,-77.339776,7,VA,Virginia,VA,Virginia,8001024,8001041,8025773,8110035,8192048,8262692,8317372,8367587,8411808
1790,"Waffle House-Staunton,VA",38.133901,-79.042422,6,VA,Virginia,VA,Virginia,8001024,8001041,8025773,8110035,8192048,8262692,8317372,8367587,8411808
1791,"Waffle House-Stephens City,VA",39.080816,-78.213600,4,VA,Virginia,VA,Virginia,8001024,8001041,8025773,8110035,8192048,8262692,8317372,8367587,8411808
1792,"Waffle House-Virginia Beach,VA",36.804371,-76.189016,4,VA,Virginia,VA,Virginia,8001024,8001041,8025773,8110035,8192048,8262692,8317372,8367587,8411808
1793,"Waffle House-Virginia Beach,VA",36.881254,-76.186480,4,VA,Virginia,VA,Virginia,8001024,8001041,8025773,8110035,8192048,8262692,8317372,8367587,8411808
1794,"Waffle House-Waynesboro,VA",38.064635,-78.937771,1,VA,Virginia,VA,Virginia,8001024,8001041,8025773,8110035,8192048,8262692,8317372,8367587,8411808
1795,"Waffle House-Winchester,VA",39.186852,-78.130910,2,VA,Virginia,VA,Virginia,8001024,8001041,8025773,8110035,8192048,8262692,8317372,8367587,8411808
1796,"Waffle House-Winchester,VA",39.165409,-78.165002,7,VA,Virginia,VA,Virginia,8001024,8001041,8025773,8110035,8192048,8262692,8317372,8367587,8411808
1797,"Waffle House-Wytheville,VA",36.947852,-81.057175,6,VA,Virginia,VA,Virginia,8001024,8001041,8025773,8110035,8192048,8262692,8317372,8367587,8411808
1798,"Waffle House-Huntington,WV",38.412195,-82.364098,2,WV,West Virginia,WV,West Virginia,1852994,1853011,1854230,1854972,1856560,1853231,1848514,1841053,1831102
1799,"Waffle House-Inwood,WV",39.362366,-78.043392,6,WV,West Virginia,WV,West Virginia,1852994,1853011,1854230,1854972,1856560,1853231,1848514,1841053,1831102
1800,"Waffle House-Martinsburg,WV",39.445517,-77.986999,4,WV,West Virginia,WV,West Virginia,1852994,1853011,1854230,1854972,1856560,1853231,1848514,1841053,1831102
1801,"Waffle House-Martinsburg,WV",39.486633,-77.957717,2,WV,West Virginia,WV,West Virginia,1852994,1853011,1854230,1854972,1856560,1853231,1848514,1841053,1831102

In [39]:
merged_pop = merged.merge(pop_df, left_on='name', right_on='State')
merged_pop.head()

,location,lat,long,score,state_abbr,name,abbreviation,State,Census,Estimates Base,2010,2011,2012,2013,2014,2015,2016
0,"Waffle House-Duluth,GA",33.991269,-84.153232,8,GA,Georgia,GA,Georgia,9687653,9688680,9713521,9811610,9914668,9984938,10087231,10199398,10310371
1,"Waffle House-Darien,GA",31.386768,-81.427065,8,GA,Georgia,GA,Georgia,9687653,9688680,9713521,9811610,9914668,9984938,10087231,10199398,10310371
2,"Waffle House-Acworth,GA",34.081955,-84.654650,7,GA,Georgia,GA,Georgia,9687653,9688680,9713521,9811610,9914668,9984938,10087231,10199398,10310371
3,"Waffle House-Acworth,GA",34.000414,-84.704073,8,GA,Georgia,GA,Georgia,9687653,9688680,9713521,9811610,9914668,9984938,10087231,10199398,10310371
4,"Waffle House-Acworth,GA",34.034899,-84.679145,10,GA,Georgia,GA,Georgia,9687653,9688680,9713521,9811610,9914668,9984938,10087231,10199398,10310371

# can reset index of  after to_frame() to get 
# count_df is just a small dataframe for conversion purposes
column name that looks like anumber has to be treated like a number, so no quotes like its a string

In [43]:
# It made a series, but you turn it into a dataframe
count_df = merged_pop.State.value_counts().to_frame()
count_df.head()

                State
Georgia           416
North Carolina    166
South Carolina    163
Florida           152
Alabama           147

In [45]:
# count_df doesn't have a column name for the state, it just has an index
calc_df = count_df.merge(pop_df, right_on='State', left_index=True)
calc_df.head()

,State,State_x,State_y,Census,Estimates Base,2010,2011,2012,2013,2014,2015,2016
15,Georgia,416,Georgia,9687653,9688680,9713521,9811610,9914668,9984938,10087231,10199398,10310371
38,North Carolina,166,North Carolina,9535483,9535688,9558915,9650963,9746175,9841590,9934399,10035186,10146788
45,South Carolina,163,South Carolina,4625364,4625410,4635943,4672637,4720760,4767894,4828430,4894834,4961119
14,Florida,152,Florida,18801310,18804592,18849098,19096952,19344156,19582022,19888741,20244914,20612439
5,Alabama,147,Alabama,4779736,4780131,4785492,4799918,4815960,4829479,4843214,4853875,4863300